import React, { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

export const translations = {
  en: {
    siteName: 'Libris',
    tagline: 'Your bilingual digital library',
    home: 'Home',
    catalog: 'Catalog',
    contact: 'Contact',
    admin: 'Admin',
    search: 'Search books...',
    allCategories: 'All Categories',
    free: 'Free',
    paid: 'Paid',
    download: 'Download PDF',
    buyNow: 'Buy Now',
    by: 'by',
    noBooks: 'No books found.',
    footerDesc: 'A curated bilingual library for Georgian and English readers.',
    footerLinks: 'Quick Links',
    footerContact: 'Contact',
    rights: '© 2024 Libris. All rights reserved.',
    contactTitle: 'Get in Touch',
    contactDesc: 'Have questions or want to purchase a book? Reach out to us.',
    emailUs: 'Email Us',
    categories: ['All', 'Fantasy', 'Detective', 'Romance', 'Cooking', 'History', 'Science', 'Poetry', 'Children'],
    adminLogin: 'Admin Login',
    email: 'Email',
    password: 'Password',
    signIn: 'Sign In',
    dashboard: 'Dashboard',
    addBook: 'Add New Book',
    manageBooks: 'Manage Books',
    titleEn: 'Title (English)',
    titleKa: 'Title (Georgian)',
    descEn: 'Description (English)',
    descKa: 'Description (Georgian)',
    category: 'Category',
    author: 'Author',
    price: 'Price (₾)',
    isFree: 'Free Book',
    coverImage: 'Cover Image',
    pdfFile: 'PDF File',
    save: 'Save Book',
    edit: 'Edit',
    delete: 'Delete',
    uploading: 'Uploading...',
    logout: 'Logout',
    confirmDelete: 'Are you sure you want to delete this book?',
    bookAdded: 'Book added successfully!',
    bookUpdated: 'Book updated successfully!',
    bookDeleted: 'Book deleted.',
    errorOccurred: 'An error occurred. Please try again.',
    heroTitle: 'Discover Stories in Two Languages',
    heroSub: 'Browse our curated collection of Georgian and English books — free and premium.',
    exploreCatalog: 'Explore Catalog',
  },
  ka: {
    siteName: 'ლიბრისი',
    tagline: 'თქვენი ორენოვანი ციფრული ბიბლიოთეკა',
    home: 'მთავარი',
    catalog: 'კატალოგი',
    contact: 'კონტაქტი',
    admin: 'ადმინი',
    search: 'წიგნების ძიება...',
    allCategories: 'ყველა კატეგორია',
    free: 'უფასო',
    paid: 'ფასიანი',
    download: 'PDF ჩამოტვირთვა',
    buyNow: 'ყიდვა',
    by: 'ავტორი',
    noBooks: 'წიგნები ვერ მოიძებნა.',
    footerDesc: 'შერჩეული ორენოვანი ბიბლიოთეკა ქართველი და ინგლისური მკითხველებისთვის.',
    footerLinks: 'სწრაფი ბმულები',
    footerContact: 'კონტაქტი',
    rights: '© 2024 ლიბრისი. ყველა უფლება დაცულია.',
    contactTitle: 'დაგვიკავშირდით',
    contactDesc: 'გაქვთ კითხვები ან გსურთ წიგნის შეძენა? დაგვიკავშირდით.',
    emailUs: 'გამოგვიგზავნე ელ-ფოსტა',
    categories: ['ყველა', 'ფენტეზი', 'დეტექტივი', 'რომანტიკა', 'კულინარია', 'ისტორია', 'მეცნიერება', 'პოეზია', 'ბავშვური'],
    adminLogin: 'ადმინ შესვლა',
    email: 'ელ-ფოსტა',
    password: 'პაროლი',
    signIn: 'შესვლა',
    dashboard: 'პანელი',
    addBook: 'წიგნის დამატება',
    manageBooks: 'წიგნების მართვა',
    titleEn: 'სათაური (ინგლისური)',
    titleKa: 'სათაური (ქართული)',
    descEn: 'აღწერა (ინგლისური)',
    descKa: 'აღწერა (ქართული)',
    category: 'კატეგორია',
    author: 'ავტორი',
    price: 'ფასი (₾)',
    isFree: 'უფასო წიგნი',
    coverImage: 'გარეკანი',
    pdfFile: 'PDF ფაილი',
    save: 'შენახვა',
    edit: 'რედაქტირება',
    delete: 'წაშლა',
    uploading: 'იტვირთება...',
    logout: 'გამოსვლა',
    confirmDelete: 'დარწმუნებული ხართ, რომ გსურთ ამ წიგნის წაშლა?',
    bookAdded: 'წიგნი წარმატებით დაემატა!',
    bookUpdated: 'წიგნი წარმატებით განახლდა!',
    bookDeleted: 'წიგნი წაიშალა.',
    errorOccurred: 'შეცდომა მოხდა. გთხოვთ სცადოთ კვლავ.',
    heroTitle: 'აღმოაჩინე ისტორიები ორ ენაზე',
    heroSub: 'დაათვალიერე ჩვენი ქართული და ინგლისური წიგნების კოლექცია — უფასო და პრემიუმ.',
    exploreCatalog: 'კატალოგის დათვალიერება',
  }
};

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('en');
  const t = translations[lang];
  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
